### ISSUE TITLE
Cannot close connections properly

### ISSUE THREAD

**Issue by firedes** [SagerNet/sing-box#1245] opened 2023-12-15 04:29 UTC
### Operating system

Linux

### System version

Openwrt 18.06

### Installation type

Original sing-box Command Line

### Version

```shell
1.7.5
```

### Description

Seems sing-box client does not close stale connections properly, would potentially exhaust memory. (In my case, memory consumption increases over time)
![image](https://github.com/SagerNet/sing-box/assets/16650765/3600f3dc-83b9-40b5-ab4d-43f3bd01a40f)
![image](https://github.com/SagerNet/sing-box/assets/16650765/11d42210-476c-4d5f-9a37-0664cc1f818a)

### Reproduction

Just run sing-box normally

**Comment by firedes** [comment] 2023-12-16 07:45
@aur3l14no Of course. `192.168.31.1` is my router's ip, `192.168.31.108` is my NAS ip, on which a mosdns is running.
```
{
  "log": {
    "disabled": false,
    "level": "info",
    "output": "box.log",
    "timestamp": true
  },
  "experimental": {
    "clash_api": {
      "external_controller": "192.168.31.1:9999",
      "external_ui": "yacd",
      "external_ui_download_url": "http://192.168.31.108:8080/download/sbox/gh-pages.zip",
      "external_ui_download_detour": "lan-out",
      "default_mode": "Rule"
    }
  },
  "dns": {
    "servers": [
      {
        "tag": "lan-dns",
        "address": "192.168.31.108",
        "detour": "lan-out"
      },
      {
        "tag": "refuse",
        "address": "rcode://name_error"
      }
    ],
    "final": "lan-dns",
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
      "type": "redirect",
      "tag": "redirect-in",
      "listen": "::",
      "listen_port": 7891,
      "sniff": true,
      "sniff_override_destination": false
    },
    {
      "type": "direct",
      "tag": "dns-in",
      "listen": "::",
      "listen_port": 7890,
      "network": "udp"
    },
    {
      "type": "tun",
      "tag": "tun-in",
      "interface_name": "tun0",
      "inet4_address": "172.19.0.1/30",
      "mtu": 9000,
      "auto_route": false,
      "strict_route": false,
      "stack": "system",
      "sniff": true,
      "sniff_override_destination": false
    }
  ],
  "outbounds": [
    {
      "type": "vless",
      "tag": "proxy-out",
      "server": "*",
      "server_port": 443,
      "uuid": "uuid",
      "flow": "xtls-rprx-vision",
      "tls": {
        "enabled": true,
        "disable_sni": false,
        "server_name": "server_name",
        "insecure": false,
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "public_key",
          "short_id": "short_id"
        }
      },
      "multiplex": {
        "enabled": false,
        "padding": false
      }
    },
    {
      "type": "direct",
      "tag": "direct-out"
    },
    {
      "type": "direct",
      "bind_interface": "br-lan",
      "tag": "lan-out"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    },
    {
      "type": "block",
      "tag": "block-out"
    }
  ],
  "route": {
    "rules": [
      {
        "type": "logical",
        "mode": "or",
        "rules": [
          {
            "inbound": "dns-in"
          },
          {
            "protocol": "dns"
          }
        ],
        "outbound": "dns-out"
      },
      {
        "geoip": [
          "private"
        ],
        "outbound": "lan-out"
      },
      {
        "domain": [
          "whatismyip.akamai.com",
        ],
        "outbound": "direct-out"
      },
      {
        "type": "logical",
        "mode": "and",
        "rules": [
          {
            "geosite": "geolocation-!cn",
            "invert": true
          },
          {
            "geosite": [
              "cn",
              "category-companies@cn"
            ],
            "geoip": "cn"
          }
        ],
        "outbound": "direct-out"
      },
      {
        "protocol": "quic",
        "outbound": "block-out"
      }
    ],
    "final": "proxy-out",
    "auto_detect_interface": false,
    "geoip": {
      "download_url": "http://192.168.31.108:8080/download/sbox/geoip.db",
      "download_detour": "lan-out"
    },
    "geosite": {
      "download_url": "http://192.168.31.108:8080/download/sbox/geosite.db",
      "download_detour": "lan-out"
    }
  }
}
```

**Comment by firedes** [comment] 2023-12-17 06:13
I've tested this on my pc(Archlinux), same issue. So maybe it is easily reproducible.

To be clarify, I had closed all websites and applications relevant to these connections over 30 minutes at least before taking this screenshot.
![image](https://github.com/SagerNet/sing-box/assets/16650765/90c3d469-eb69-468f-be6e-74db01f61e7a)

```
{
  "log": {
    "disabled": false,
    "level": "debug",
    "output": "box.log",
    "timestamp": true
  },
  "experimental": {
    "clash_api": {
      "external_controller": "192.168.31.47:9999",
      "external_ui": "yacd",
      "external_ui_download_url": "http://192.168.31.108:8080/download/sbox/gh-pages.zip",
      "external_ui_download_detour": "direct-out",
      "default_mode": "Rule"
    }
  },
  "dns": {
    "servers": [
      {
        "tag": "google",
        "address": "tls://8.8.8.8",
        "detour": "proxy-out"
      },
      {
        "tag": "local",
        "address": "223.5.5.5",
        "detour": "direct-out"
      }
    ],
    "rules": [
      {
        "type": "logical",
        "mode": "and",
        "rules": [
          {
            "geosite": "geolocation-!cn",
            "invert": true
          },
          {
            "geosite": [
              "cn",
              "category-companies@cn"
            ]
          }
        ],
        "server": "local"
      }
    ],
    "strategy": "ipv4_only"
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "interface_name": "tun0",
      "inet4_address": "172.19.0.1/30",
      "mtu": 9000,
      "auto_route": true,
      "strict_route": true,
      "stack": "system",
      "sniff": true,
      "sniff_override_destination": false,
      "sniff_timeout": "300ms",
      "domain_strategy": "prefer_ipv4"
    }
  ],
  "outbounds": [
    {
      "type": "vless",
      "tag": "proxy-out",
      "server": "server",
      "server_port": 443,
      "uuid": "uuid",
      "flow": "xtls-rprx-vision",
      "tls": {
        "enabled": true,
        "disable_sni": false,
        "server_name": "server_name",
        "insecure": false,
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        },
        "reality": {
          "enabled": true,
          "public_key": "public_key",
          "short_id": "short_id"
        }
      },
      "multiplex": {
        "enabled": false,
        "padding": false
      }
    },
    {
      "type": "direct",
      "tag": "direct-out"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "rules": [
      {
        "protocol": "dns",
        "outbound": "dns-out"
      },
      {
        "geoip": [
          "private"
        ],
        "outbound": "direct-out"
      },
      {
        "port": [
          28287
        ],
        "outbound": "direct-out"
      },
      {
        "domain": [
          "whatismyip.akamai.com",
        ],
        "outbound": "direct-out"
      },
      {
        "type": "logical",
        "mode": "and",
        "rules": [
          {
            "geosite": "geolocation-!cn",
            "invert": true
          },
          {
            "geosite": [
              "cn",
              "category-companies@cn"
            ],
            "geoip": "cn"
          }
        ],
        "outbound": "direct-out"
      }
    ],
    "auto_detect_interface": true,
    "geoip": {
      "download_url": "http://192.168.31.108:8080/download/sbox/geoip.db",
      "download_detour": "direct-out"
    },
    "geosite": {
      "download_url": "http://192.168.31.108:8080/download/sbox/geosite.db",
      "download_detour": "direct-out"
    }
  }
}
```

**Comment by SasukeFreestyle** [comment] 2023-12-17 15:48
I also have this problem.
Memory increases over time to the point that it uses over 6GB of RAM, sing-box process then uses over 50% CPU then process freezes and/or system because unusable

A quick fix i did was to add this to systemd, once sing-box reaches 4500MB of RAM, its auto-restarted.
```
Restart=always
MemoryMax=4500M
MemoryLimit=4500M
```
Ubuntu 22.04.3 LTS

config file.

```json
{
   "log":{
      "level":"info",
      "timestamp":true
   },
   "inbounds":[
      {
         "type":"hysteria2",
         "tag":"hy2-in-80",
         "listen":"::",
         "listen_port":80,
         "sniff":true,
         "sniff_override_destination":true,
         "domain_strategy":"prefer_ipv4",
         "up_mbps":0,
         "down_mbps":0,
         "obfs":{
            "type":"salamander",
            "password":"X"
         },
         "users":[
            {
               "name":"user",
               "password":"X"
            }
         ],
         "ignore_client_bandwidth":true,
         "tls":{
            "enabled":true,
            "certificate_path":"X",
            "key_path":"X"
         }
      },
	        {
         "type":"hysteria2",
         "tag":"hy2-in-443",
         "listen":"::",
         "listen_port":80,
         "sniff":true,
         "sniff_override_destination":true,
         "domain_strategy":"prefer_ipv4",
         "up_mbps":0,
         "down_mbps":0,
         "obfs":{
            "type":"salamander",
            "password":"X"
         },
         "users":[
            {
               "name":"user",
               "password":"X"
            }
         ],
         "ignore_client_bandwidth":true,
         "tls":{
            "enabled":true,
            "certificate_path":"X",
            "key_path":"X"
         }
      }
   ],
   "outbounds":[
      {
         "type":"direct",
         "tag":"direct"
      },
      {
         "type":"block",
         "tag":"block"
      },
      {
         "type":"dns",
         "tag":"dns-out"
      }
   ],
   "dns":{
      "disable_cache":true,
      "servers":[
         {
            "tag":"dns-out",
            "address":"udp://127.0.0.53",
            "address_strategy":"prefer_ipv4",
            "strategy":"prefer_ipv4",
            "detour":"direct"
         }
      ]
   },
   "route":{
      "rules":[
         {
            "ip_is_private":true,
            "outbound":"block"
         },
         {
            "rule_set":"geoip-cn",
            "outbound":"block"
         },
         {
            "rule_set":"geoip-ir",
            "outbound":"block"
         },
         {
            "rule_set":"geosite-ir",
            "outbound":"block"
         },
         {
            "protocol":"dns",
            "outbound":"dns-out"
         },
         {
            "outbound":"block",
            "domain_suffix":[
               "bitstamp.net",
               "dt.beyla.site",
               "beyla.site"
            ]
         }
      ],
      "rule_set":[
         {
            "tag":"geoip-cn",
            "type":"local",
            "format":"binary",
            "path":"X"
         },
         {
            "tag":"geoip-ir",
            "type":"local",
            "format":"binary",
            "path":"X"
         },
         {
            "tag":"geosite-ir",
            "type":"local",
            "format":"binary",
            "path":"X"
         }
      ],
      "auto_detect_interface":true
   }
}
```

**Comment by lux5am** [comment] 2023-12-18 03:22
Uses grpc and the memory consumption increased very fast. Just 5 minutes, downloaded 500mb the memory consumption already 200mb. Plain ws is much lower but still raise overtime without going down.

**Comment by nekohasekai** [comment] 2023-12-20 11:25
Since you didn't provide a process for reproducing the issue locally, I can assume you are an end user who lacks the knowledge. Since you are reporting on an issue that most people haven't reported, and your issue area has become a gathering place for spam feedback without information, I will close it. I would suggest you use a different protocol or switch to a different project.

**Closed** 2023-12-20 11:26 UTC
Labels: not following template, from end user
